name: Build

on:
  workflow_call:
    inputs:
      upload-artifacts:
        description: Upload build artifacts
        type: boolean
        default: false
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          make build
          mv c5s c5s-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        if: inputs.upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: c5s-${{ matrix.goos }}-${{ matrix.goarch }}
          path: c5s-${{ matrix.goos }}-${{ matrix.goarch }}
          retention-days: 7
